/**
 * ============================================================================
 * BaseEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const BaseEngine = {DECOR:{wall:{default:{name:"白色墙壁",cost:0},blue:{name:"海洋蓝",cost:100},green:{name:"森林绿",cost:100},red:{name:"火焰红",cost:150},night:{name:"星空紫",cost:200}},floor:{default:{name:"木质地板",cost:0},tile:{name:"瓷砖",cost:80},grass:{name:"草地",cost:120},stone:{name:"石板",cost:150}},furniture:{desk:{name:"📚 学习桌",cost:200,desc:"+10% 答题经验"},shelf:{name:"📖 书架",cost:250,desc:"展示收藏"},trophy:{name:"🏆 奖杯柜",cost:300,desc:"展示成就"},plant:{name:"🌿 盆栽",cost:80,desc:"美化空间"},poster:{name:"🖼️ 防灾海报",cost:120,desc:"知识提醒"}}},buy(category,itemId){var item=this.DECOR[category][itemId];item&&0!==item.cost&&(GameState.spendCoins(item.cost)?(GameState._data.baseDecor||(GameState._data.baseDecor={wall:"default",floor:"default",furniture:[]}),"wall"===category||"floor"===category?GameState._data.baseDecor[category]=itemId:GameState._data.baseDecor.furniture.includes(itemId)||GameState._data.baseDecor.furniture.push(itemId),GameState.save(),Modal.show("🏠 装饰成功",item.name+" 已布置！","🏠")):Modal.show("❌ 金币不足","需要 "+item.cost+" 金币"))},setDecor(category,itemId){GameState._data.baseDecor||(GameState._data.baseDecor={wall:"default",floor:"default",furniture:[]}),GameState._data.baseDecor[category]=itemId,GameState.save()},render(){var base=GameState._data.baseDecor||{wall:"default",floor:"default",furniture:[]},html='<div style="padding:16px"><h3>🏠 防灾基地</h3>';for(var cat in html+='<div style="background:linear-gradient(135deg,rgba(30,30,60,0.8),rgba(20,20,40,0.8));border-radius:16px;padding:20px;margin:12px 0;text-align:center">',html+='<div style="font-size:48px;margin:10px">🏠</div>',html+='<div style="color:rgba(255,255,255,0.6);font-size:13px">我的防灾基地</div>',base.furniture.length>0&&(html+='<div style="margin-top:12px;display:flex;gap:8px;justify-content:center;flex-wrap:wrap">',base.furniture.forEach(function(f){var item=BaseEngine.DECOR.furniture[f];item&&(html+='<span style="font-size:24px">'+item.name.charAt(0)+"</span>")}),html+="</div>"),html+="</div>",this.DECOR){for(var itemId in html+='<div style="margin:12px 0"><div style="color:var(--accent,#00d4ff);font-weight:700;margin-bottom:6px">'+("wall"===cat?"🎨 墙壁":"floor"===cat?"🧱 地板":"🪑 家具")+"</div>",this.DECOR[cat]){var item=this.DECOR[cat][itemId],isCurrent="wall"===cat||"floor"===cat?base[cat]===itemId:base.furniture.includes(itemId);html+='<div class="daily-task-item"><span>'+item.name+"</span>"+(item.desc?'<span style="font-size:11px;color:rgba(255,255,255,0.5)">'+item.desc+"</span>":"")+(isCurrent?'<span style="color:#00e676">已拥有</span>':0===item.cost?'<span style="color:rgba(255,255,255,0.3)">默认</span>':'<span style="cursor:pointer;color:#ffd700" onclick="BaseEngine.buy(\''+cat+"','"+itemId+"')\">💰"+item.cost+"</span>")+"</div>"}html+="</div>"}return html+="</div>"}};
