/**
 * ============================================================================
 * CardSynthesisEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const CardSynthesisEngine = {RARITY_ORDER:["common","rare","epic","legendary"],getSynthesizable(){var cards=GameState._data.cards||[],groups=(GameState._data.cardLevels,{});cards.forEach(function(id){var card="undefined"!=typeof ALL_CARDS?ALL_CARDS.find(function(c){return c.id===id}):null;if(card){var rarity=card.rarity||"common";if("legendary"!==rarity){var key=card.type+"_"+rarity;groups[key]||(groups[key]=[]),groups[key].push(card)}}});var result=[];for(var key in groups)groups[key].length>=3&&result.push({key:key,type:groups[key][0].type,rarity:groups[key][0].rarity,count:groups[key].length,cards:groups[key]});return result},synthesize(key){var cards=GameState._data.cards||[],groups={};cards.forEach(function(id){var card="undefined"!=typeof ALL_CARDS?ALL_CARDS.find(function(c){return c.id===id}):null;if(card){var k=card.type+"_"+(card.rarity||"common");groups[k]||(groups[k]=[]),groups[k].push(card)}});var group=groups[key];if(!group||group.length<3)Modal.show("❌ 材料不足","需要 3 张同类型同稀有度卡牌");else{var srcRarity=group[0].rarity||"common",srcType=group[0].type,idx=this.RARITY_ORDER.indexOf(srcRarity);if(idx>=this.RARITY_ORDER.length-1)Modal.show("❌ 已满级","传说卡无法继续合成");else{var targetRarity=this.RARITY_ORDER[idx+1],pool=ALL_CARDS.filter(function(c){return c.type===srcType&&c.rarity===targetRarity});if(0===pool.length&&(pool=ALL_CARDS.filter(function(c){return c.rarity===targetRarity})),0!==pool.length){var targetCard=pool[Math.floor(Math.random()*pool.length)],removed=0,newCards=[];cards.forEach(function(id){var card=ALL_CARDS.find(function(c){return c.id===id});card&&card.type===srcType&&(card.rarity||"common")===srcRarity&&removed<3?removed++:newCards.push(id)}),newCards.push(targetCard.id),GameState._data.cards=newCards,GameState._data.stats.cardsSynthesized=(GameState._data.stats.cardsSynthesized||0)+1,GameState.addExp(50),GameState.save();var labels={common:"普通",rare:"稀有",epic:"史诗",legendary:"传说"};Modal.show("🧪 合成成功！","3 × "+labels[srcRarity]+" → 1 × "+labels[targetRarity]+"<br/>"+targetCard.name,"🧪")}else Modal.show("❌ 无目标卡","没有可合成的目标卡牌")}}},render(){var items=this.getSynthesizable();if(0===items.length)return'<div style="padding:20px;text-align:center;color:rgba(255,255,255,0.5)">暂无可合成的卡牌<br/>需要 3 张同类型同稀有度</div>';var html='<div style="padding:16px"><h3>🧪 卡牌合成</h3>',labels={common:"普通",rare:"稀有",epic:"史诗"},self=this;return items.forEach(function(item){var nextIdx=self.RARITY_ORDER.indexOf(item.rarity)+1,next=self.RARITY_ORDER[nextIdx]||"legendary";html+='<div class="daily-task-item" onclick="CardSynthesisEngine.synthesize(\''+item.key+'\')" style="cursor:pointer"><span>'+item.count+" × "+labels[item.rarity]+" "+item.type+'</span><span style="color:#ffd700">→ 1 × '+labels[next]+"</span></div>"}),html+="</div>"}};
