/**
 * ============================================================================
 * CardDropEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const CardDropEngine = {RARITY:{common:{name:"普通",color:"#9e9e9e",chance:.5,icon:"⬜"},fine:{name:"精良",color:"#4caf50",chance:.3,icon:"🟢"},epic:{name:"史诗",color:"#2196f3",chance:.13,icon:"🔵"},legendary:{name:"传说",color:"#9c27b0",chance:.06,icon:"🟣"},mythic:{name:"神话",color:"#ff9800",chance:.01,icon:"🟡"}},rollCard:function(combo){combo=combo||0;var bonus=Math.min(.02*combo,.3),roll=Math.random()-bonus;return roll<.01?"mythic":roll<.07?"legendary":roll<.2?"epic":roll<.5?"fine":"common"},dropCard:function(cardId,rarity){var card=ALL_CARDS.find(function(c){return c.id===cardId});if(card){var r=this.RARITY[rarity],overlay=document.createElement("div");overlay.className="card-drop-overlay",overlay.style.cssText="position:fixed;inset:0;z-index:20000;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,0.7);backdrop-filter:blur(8px);opacity:0;transition:opacity 0.3s;cursor:pointer;",overlay.innerHTML='<div style="background:linear-gradient(135deg,'+r.color+"22,"+r.color+"44);border:3px solid "+r.color+";border-radius:20px;padding:30px;max-width:320px;width:90%;text-align:center;transform:scale(0) rotateY(180deg);animation:cardReveal 0.8s cubic-bezier(0.34,1.56,0.64,1) 0.3s forwards;box-shadow:0 0 30px "+r.color+"66,0 0 60px "+r.color+'33;"><div style="font-size:3rem;margin-bottom:12px;">'+r.icon+'</div><div style="font-size:0.8rem;color:'+r.color+';text-transform:uppercase;letter-spacing:2px;margin-bottom:8px;">'+r.name+'</div><div style="font-size:2rem;margin-bottom:12px;">'+(card.icon||"📚")+'</div><div style="font-size:1.1rem;font-weight:700;margin-bottom:8px;">'+(card.title||card.id)+'</div><div style="margin-top:16px;font-size:0.75rem;color:var(--text-tertiary);">点击继续</div></div>',document.body.appendChild(overlay),requestAnimationFrame(function(){overlay.style.opacity="1"}),overlay.addEventListener("click",function(){overlay.style.opacity="0",setTimeout(function(){overlay.remove()},300)}),setTimeout(function(){overlay.parentNode&&(overlay.style.opacity="0",setTimeout(function(){overlay.remove()},300))},4e3);var data=GameState._data;data&&(data.cardCollection||(data.cardCollection=[]),-1===data.cardCollection.indexOf(cardId)&&(data.cardCollection.push(cardId),GameState.save()))}},tryDrop:function(combo){if(combo=combo||0,!(Math.random()>.3)){var rarity=this.rollCard(combo),knowledgeCards=ALL_CARDS.filter(function(c){return"equip"!==c.disaster}),randomCard=knowledgeCards[Math.floor(Math.random()*knowledgeCards.length)];randomCard&&setTimeout(function(){CardDropEngine.dropCard(randomCard.id,rarity)},500)}}};
