/**
 * ============================================================================
 * EasterEggEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const EasterEggEngine = {EGGS:[{id:"konami",name:"🎮 经典秘籍",desc:"发现隐藏的科纳米代码",icon:"🎮",secret:!0},{id:"click100",name:"🖱️ 点击大师",desc:"单次会话点击100次",icon:"🖱️",secret:!1},{id:"night_owl",name:"🦉 夜猫子",desc:"深夜12点后登录",icon:"🦉",secret:!0},{id:"early_bird",name:"🐦 早起鸟",desc:"早上6点前登录",icon:"🐦",secret:!0},{id:"full_codex",name:"📚 百科全书",desc:"解锁全部图鉴",icon:"📚",secret:!1},{id:"card_master",name:"🃏 卡牌大师",desc:"收集全部369张卡",icon:"🃏",secret:!1},{id:"lucky7",name:"🎰 幸运7",desc:"连续7次开到稀有卡",icon:"🎰",secret:!0},{id:"speed_demon",name:"⚡ 速度恶魔",desc:"答题时间<3秒且正确",icon:"⚡",secret:!0},{id:"collector",name:"🎨 收藏家",desc:"解锁全部主题",icon:"🎨",secret:!1},{id:"survivor",name:"💀 幸存者",desc:"HP为1时答对题目",icon:"💀",secret:!0},{id:"no_damage",name:"🛡️ 完美防御",desc:"Boss战零伤害通关",icon:"🛡️",secret:!1},{id:"coin_king",name:"👑 金币之王",desc:"累计获得10000金币",icon:"👑",secret:!1},{id:"level_50",name:"⭐ 防灾达人",desc:"达到50级",icon:"⭐",secret:!1},{id:"marathon",name:"🏃 马拉松",desc:"连续答题100道",icon:"🏃",secret:!1},{id:"pet_lover",name:"🐾 宠物达人",desc:"解锁全部宠物",icon:"🐾",secret:!1}],isFound:eggId=>(GameState._data.eggsFound||[]).includes(eggId),found(eggId){if(!this.isFound(eggId)){var eggs=GameState._data.eggsFound||[];eggs.push(eggId),GameState._data.eggsFound=eggs,GameState._data.stats.eggsFound=eggs.length,GameState.addExp(100),GameState.addCoins(200),GameState.save();var egg=this.EGGS.find(function(e){return e.id===eggId});egg&&Modal.show("🥚 发现隐藏彩蛋！",egg.icon+" "+egg.name+"<br/>"+egg.desc+"<br/>+200金币 +100经验","🥚")}},render(){var found=GameState._data.eggsFound||[],html='<div style="padding:16px"><h3>🥚 隐藏彩蛋</h3>';return html+='<div style="text-align:center;margin:12px 0;font-size:14px;color:rgba(255,255,255,0.6)">已发现 '+found.length+"/"+this.EGGS.length+"</div>",this.EGGS.forEach(function(e){var isFound=found.includes(e.id),showName=isFound||!e.secret;html+='<div class="daily-task-item" style="'+(isFound?"":"opacity:0.4")+'"><span>'+(isFound?e.icon:"❓")+" "+(showName?e.name:"???")+'</span><span style="font-size:11px;color:rgba(255,255,255,0.5)">'+(isFound?e.desc:e.secret?"隐藏彩蛋":e.desc)+"</span></div>"}),html+="</div>"}};
