/**
 * ============================================================================
 * MemoryGameV2
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const MemoryGameV2 = {_cards:[],_flipped:[],_matched:0,_total:0,_moves:0,_active:!1,_icons:["🌊","🔥","🌪️","❄️","🏜️","🌋","⚡","🧊"],init(size){var pairs="hard"===size?12:"medium"===size?8:6;this._total=pairs,this._matched=0,this._moves=0,this._flipped=[],this._active=!0;for(var icons=this._icons.slice(0,pairs),deck=icons.concat(icons),i=deck.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=deck[i];deck[i]=deck[j],deck[j]=t}this._cards=deck.map(function(icon,idx){return{icon:icon,id:idx,flipped:!1,matched:!1}}),PageManager.navigate("minigame"),this._render()},_render(){var el=document.getElementById("minigameContent");if(el){var cols=this._total<=6||this._total<=8?4:6,html='<div class="v10-card" style="padding:16px;"><div style="display:flex;justify-content:space-between;margin-bottom:12px;"><span style="color:rgba(255,255,255,0.5);font-size:0.8rem;">步数: '+this._moves+'</span><span style="color:rgba(255,255,255,0.5);font-size:0.8rem;">已配对: '+this._matched+"/"+this._total+'</span></div><div style="display:grid;grid-template-columns:repeat('+cols+',1fr);gap:8px;">';this._cards.forEach(function(card,i){var display=card.matched||card.flipped?card.icon:"❓",bg=card.matched?"rgba(0,230,118,0.15)":card.flipped?"rgba(0,212,255,0.15)":"rgba(255,255,255,0.04)";html+='<div onclick="MemoryGameV2.flip('+i+')" style="aspect-ratio:1;display:flex;align-items:center;justify-content:center;font-size:1.5rem;background:'+bg+';border-radius:10px;cursor:pointer;border:1px solid rgba(255,255,255,0.06);transition:all 0.3s;">'+display+"</div>"}),html+="</div></div>",el.innerHTML=html}},flip(idx){if(this._active){var card=this._cards[idx];if(!(card.flipped||card.matched||this._flipped.length>=2))if(card.flipped=!0,this._flipped.push(idx),AudioManager.play("flip"),2===this._flipped.length){this._moves++;var a=this._cards[this._flipped[0]],b=this._cards[this._flipped[1]],self=this;a.icon===b.icon?(a.matched=b.matched=!0,this._matched++,AudioManager.play("correct"),this._flipped=[],this._render(),this._matched===this._total&&setTimeout(function(){self._finish()},500)):(setTimeout(function(){a.flipped=b.flipped=!1,self._flipped=[],self._render()},800),this._render())}else this._render()}},_finish(){this._active=!1;var stars=this._moves<=this._total+2?3:this._moves<=2*this._total?2:1,coins=20*stars;GameState.set("coins",(GameState.get("coins")||0)+coins),Modal.show("🧩 记忆翻牌完成","⭐".repeat(stars)+"<br/>步数: "+this._moves+"<br/>💰 +"+coins+" 金币","🧩")}};
