/**
 * ============================================================================
 * OutfitEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const OutfitEngine = {ITEMS:{head:{helmet:{name:"⛑️ 安全帽",bonus:"防御 +10%",cost:100},cap:{name:"🧢 棒球帽",bonus:"速度 +5%",cost:80},mask:{name:"😷 防毒面具",bonus:"毒气题 +20%",cost:200}},body:{fire:{name:"🧥 消防服",bonus:"火灾题 +15%",cost:300},vest:{name:"🦺 救生衣",bonus:"水灾题 +15%",cost:300},suit:{name:"🥼 防护服",bonus:"疫情题 +15%",cost:300}},gloves:{fireg:{name:"🧤 防火手套",bonus:"火灾题 +10%",cost:150},rubber:{name:"🧤 橡胶手套",bonus:"电力题 +10%",cost:150}},shoes:{boots:{name:"👢 防水靴",bonus:"水灾题 +10%",cost:150},climb:{name:"🥾 登山鞋",bonus:"泥石流题 +10%",cost:150}},accessory:{radio:{name:"📻 对讲机",bonus:"Boss战 +10%",cost:200},kit:{name:"🧰 急救包",bonus:"每局回血1次",cost:250},torch:{name:"🔦 手电筒",bonus:"暗场景 +15%",cost:120}}},equip(slot,itemId){GameState._data.outfits||(GameState._data.outfits={}),GameState._data.outfits[slot]=itemId,GameState.save();var item=this.ITEMS[slot][itemId];Modal.show("🎭 装备成功",item.name+" 已装备到 "+slot,"🎭")},unequip(slot){GameState._data.outfits||(GameState._data.outfits={}),GameState._data.outfits[slot]="",GameState.save()},buy(slot,itemId){var item=this.ITEMS[slot][itemId];if(item)if(GameState.spendCoins(item.cost)){GameState._data.equipment||(GameState._data.equipment=[]);var key=slot+"_"+itemId;GameState._data.equipment.includes(key)||GameState._data.equipment.push(key),GameState.save(),this.equip(slot,itemId)}else Modal.show("❌ 金币不足","需要 "+item.cost+" 金币")},isOwned:(slot,itemId)=>(GameState._data.equipment||[]).includes(slot+"_"+itemId),render(){var outfits=GameState._data.outfits||{},html='<div style="padding:16px"><h3>🎭 角色换装</h3>',slotNames={head:"头部",body:"身体",gloves:"手套",shoes:"鞋子",accessory:"配件"};for(var slot in this.ITEMS){for(var itemId in html+='<div style="margin:12px 0"><div style="color:var(--accent,#00d4ff);font-weight:700;margin-bottom:6px">'+slotNames[slot]+" "+(outfits[slot]?"✅":"⬜")+"</div>",this.ITEMS[slot]){var item=this.ITEMS[slot][itemId],owned=this.isOwned(slot,itemId),equipped=outfits[slot]===itemId;html+='<div class="daily-task-item" style="'+(equipped?"border-color:rgba(0,212,255,0.5)":"")+'"><span>'+item.name+'</span><span style="font-size:11px;color:rgba(255,255,255,0.5)">'+item.bonus+"</span>"+(equipped?'<span style="color:#00e676">装备中</span>':owned?'<span style="cursor:pointer;color:#00d4ff" onclick="OutfitEngine.equip(\''+slot+"','"+itemId+"')\">装备</span>":'<span style="cursor:pointer;color:#ffd700" onclick="OutfitEngine.buy(\''+slot+"','"+itemId+"')\">💰"+item.cost+"</span>")+"</div>"}html+="</div>"}return html+"</div>"}};
