/**
 * ============================================================================
 * PetEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const PetEngine = {PETS:{dragon:{name:"🐉 地龙宝宝",skill:"答错显示提示",icon:"🐉",unlock:"开箱获得",type:"general"},flame:{name:"🔥 火焰精灵",skill:"火灾题 +20% 金币",icon:"🔥",unlock:"击败火焰Boss",type:"fire"},water:{name:"🌊 水滴精灵",skill:"连击 +1",icon:"🌊",unlock:"收集50张水灾卡",type:"flood"},wind:{name:"🌪️ 旋风小子",skill:"答题时间 +5s",icon:"🌪️",unlock:"等级20",type:"typhoon"},ice:{name:"❄️ 冰晶兽",skill:"答错不扣HP",icon:"❄️",unlock:"成就解锁",type:"snowstorm"},lava:{name:"🌋 岩浆龙",skill:"Boss战伤害 +20%",icon:"🌋",unlock:"击败火山Boss",type:"fire"},clean:{name:"🦠 净化精灵",skill:"每日回血",icon:"🦠",unlock:"签到30天",type:"general"},sun:{name:"☀️ 太阳鸟",skill:"金币 +15%",icon:"☀️",unlock:"图鉴50%",type:"drought"}},unlock(petId){if(GameState._data.pets||(GameState._data.pets={}),GameState._data.pets[petId])return!1;GameState._data.pets[petId]={level:1,exp:0,unlocked:Date.now()},GameState._data.stats.petsUnlocked=Object.keys(GameState._data.pets).length,GameState.save();var pet=this.PETS[petId];return Modal.show("🐉 获得新宠物！",pet.icon+" "+pet.name+"<br/>"+pet.skill,"🐉"),!0},setActive(petId){GameState._data.pets&&GameState._data.pets[petId]&&(GameState._data.activePet=petId,GameState.save())},getActive(){var id=GameState._data.activePet;return id&&this.PETS[id]?{id:id,data:GameState._data.pets[id],info:this.PETS[id]}:null},feed(petId){if(GameState._data.pets&&GameState._data.pets[petId])if(GameState.spendCoins(20)){var pet=GameState._data.pets[petId];pet.exp=(pet.exp||0)+10;var needed=30*pet.level;pet.exp>=needed&&(pet.exp-=needed,pet.level++),GameState.save(),Modal.show("🐉 喂食成功",this.PETS[petId].icon+" "+this.PETS[petId].name+" Lv."+pet.level,"🐉")}else Modal.show("❌ 金币不足","喂食需要 20 金币")},getSkillBonus(){var active=this.getActive();if(!active)return{};var id=active.id;return"flame"===id||"lava"===id?{coinBonus:.2}:"water"===id?{comboBonus:1}:"wind"===id?{timeBonus:5}:"ice"===id?{noDamage:!0}:"sun"===id?{coinBonus:.15}:"clean"===id?{dailyHeal:!0}:"dragon"===id?{showHint:!0}:{}},render(){var owned=GameState._data.pets||{},active=GameState._data.activePet,html='<div style="padding:16px"><h3>🐉 宠物系统</h3>';for(var id in this.PETS){var p=this.PETS[id],isOwned=!!owned[id],isActive=active===id;html+='<div class="daily-task-item" style="'+(isActive?"border-color:rgba(255,215,0,0.5);background:rgba(255,215,0,0.08)":"")+'"><span style="font-size:24px">'+p.icon+'</span><div><div style="font-weight:700">'+p.name+(isActive?" 🏷️":"")+'</div><div style="font-size:11px;color:rgba(255,255,255,0.5)">'+(isOwned?p.skill+" Lv."+(owned[id].level||1):"🔒 "+p.unlock)+"</div></div>"+(isOwned&&!isActive?'<span style="cursor:pointer;color:#00d4ff" onclick="PetEngine.setActive(\''+id+"');PageManager.navigate('pets')\">出战</span>":"")+(isOwned?'<span style="cursor:pointer;color:#ffd700;margin-left:8px" onclick="PetEngine.feed(\''+id+"')\">🍖</span>":"")+"</div>"}return html+"</div>"}};
