/**
 * ============================================================================
 * ReactionGameV2
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const ReactionGameV2 = {_questions:[],_idx:0,_score:0,_lives:3,_active:!1,_timer:null,_time:8,init(){var cards="undefined"!=typeof ALL_CARDS?ALL_CARDS.filter(function(c){return"equip"!==c.disaster}):[];if(cards.length){var shuffled=cards.slice().sort(function(){return Math.random()-.5});this._questions=shuffled.slice(0,15),this._idx=0,this._score=0,this._lives=3,this._active=!0,this._time=8,PageManager.navigate("minigame"),this._nextQ()}else V10Toast.error("题库为空")},_nextQ(){if(this._idx>=this._questions.length||this._lives<=0)this._finish();else{var q=this._questions[this._idx];this._currentQ=q,this._time=8;var el=document.getElementById("minigameContent");if(el){var html='<div class="v10-card" style="padding:20px;"><div style="display:flex;justify-content:space-between;margin-bottom:12px;"><span style="color:rgba(255,255,255,0.4);font-size:0.8rem;">'+"❤️".repeat(this._lives)+'</span><span class="v10-badge" style="background:rgba(255,68,68,0.15);color:#FF4444;">⏱️ <span id="rg2Timer">8</span>s</span><span style="color:rgba(255,255,255,0.4);font-size:0.8rem;">'+(this._idx+1)+"/"+this._questions.length+" | "+this._score+'分</span></div><div class="v10-progress" style="margin-bottom:16px;"><div class="v10-progress-fill" style="width:'+this._idx/this._questions.length*100+'%;background:linear-gradient(90deg,#FF5252,#FF9800);"></div></div><p style="color:rgba(255,255,255,0.85);font-size:0.95rem;margin-bottom:16px;line-height:1.6;">'+q.zh.q+"</p>";q.zh.opts.forEach(function(opt,i){html+='<div onclick="ReactionGameV2.answer('+i+')" style="padding:12px 16px;margin:6px 0;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.06);border-radius:10px;cursor:pointer;color:rgba(255,255,255,0.85);font-size:0.85rem;"><span style="color:var(--cyber-blue);margin-right:8px;">'+["A","B","C","D"][i]+"</span>"+opt+"</div>"}),html+="</div>",el.innerHTML=html;var self=this;clearInterval(this._timer),this._timer=setInterval(function(){self._time--;var te=document.getElementById("rg2Timer");te&&(te.textContent=self._time),self._time<=0&&(clearInterval(self._timer),self._timeUp())},1e3)}}},answer(idx){if(this._active){clearInterval(this._timer),idx===this._currentQ.zh.ans?(this._score+=10+2*this._time,AudioManager.play("correct")):(this._lives--,AudioManager.play("wrong")),this._idx++;var self=this;setTimeout(function(){self._nextQ()},500)}},_timeUp(){this._lives--,this._idx++,AudioManager.play("wrong"),V10Toast.error("⏰ 时间到！");var self=this;setTimeout(function(){self._nextQ()},500)},_finish(){this._active=!1,clearInterval(this._timer);var coins=Math.floor(this._score/2);GameState.set("coins",(GameState.get("coins")||0)+coins),Modal.show("⚡ 快速反应结束","🏆 得分: "+this._score+"<br/>❤️ 剩余: "+this._lives+"<br/>💰 奖励: +"+coins+" 金币","⚡")}};
