/**
 * ============================================================================
 * ReactionEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const ReactionEngine = {rounds:0,totalRounds:10,scores:[],active:!1,showingTarget:!1,targetTimeout:null,startTime:0,init(){PageManager.navigate("reaction"),this.active=!0,this.rounds=0,this.scores=[],this._showReady(),AudioManager.play("start")},_showReady(){var infoEl=document.getElementById("reactionInfo"),areaEl=document.getElementById("reactionArea");infoEl&&(infoEl.textContent="准备..."),areaEl&&(areaEl.style.background="rgba(255,255,255,0.03)",areaEl.innerHTML='<div style="font-size:48px;">🎯</div><div style="font-size:16px;color:rgba(255,255,255,0.5);margin-top:12px;">等待目标出现...</div>',areaEl.onclick=null);var self=this,delay=1500+3e3*Math.random();this.targetTimeout=setTimeout(function(){self._showTarget()},delay)},_showTarget(){var infoEl=document.getElementById("reactionInfo"),areaEl=document.getElementById("reactionArea");if(infoEl&&(infoEl.textContent="点击！"),areaEl){var colors=["#FF006E","#00D4FF","#FFD700","#00E676","#AB47BC"],color=colors[Math.floor(Math.random()*colors.length)],size=60+40*Math.random(),x=20+60*Math.random(),y=20+60*Math.random();areaEl.style.background="rgba(255,255,255,0.03)",areaEl.innerHTML='<div style="font-size:'+size+"px;position:absolute;left:"+x+"%;top:"+y+"%;transform:translate(-50%,-50%);filter:drop-shadow(0 0 20px "+color+');">⚡</div>',areaEl.onclick=function(){ReactionEngine._hit()}}this.startTime=Date.now(),this.showingTarget=!0},_hit(){if(this.showingTarget){var reactionTime=Date.now()-this.startTime;this.showingTarget=!1,this.scores.push(reactionTime),this.rounds++;var infoEl=document.getElementById("reactionInfo");if(document.getElementById("reactionArea"),infoEl){var rating=reactionTime<200?"超神！":reactionTime<350?"优秀！":reactionTime<500?"不错！":"继续加油！";infoEl.textContent=reactionTime+"ms - "+rating}AudioManager.play("correct"),"function"==typeof correctEffect&&correctEffect();var self=this;setTimeout(function(){self.rounds>=self.totalRounds?self._gameOver():self._showReady()},1200)}},_gameOver(){this.active=!1;var avg=Math.round(this.scores.reduce(function(a,b){return a+b},0)/this.scores.length),best=Math.min.apply(null,this.scores),coins=Math.max(10,Math.floor(500/avg)),xp=Math.floor(.5*coins);void 0!==GameState&&GameState._data&&(GameState._data.coins=(GameState._data.coins||0)+coins,void 0!==LevelEngine&&LevelEngine.addXP(xp),"function"==typeof GameState.save&&GameState.save()),avg<300?(AudioManager.play("victory"),"function"==typeof victoryEffect&&victoryEffect(),Modal.show("⚡ 反射神经MAX！","平均 "+avg+"ms | 最快 "+best+"ms<br><br>你是闪电侠吗？！<br><br>💰 +"+coins+" 金币<br>⭐ +"+xp+" 经验","🏆")):avg<500?(AudioManager.play("fanfare"),Modal.show("⚡ 反应不错！","平均 "+avg+"ms | 最快 "+best+"ms<br><br>💰 +"+coins+" 金币<br>⭐ +"+xp+" 经验","👍")):(AudioManager.play("game_over"),Modal.show("⚡ 继续练习！","平均 "+avg+"ms | 最快 "+best+"ms<br><br>多练习会更快哦！<br><br>💰 +"+coins+" 金币","💪"))}};
