/**
 * ============================================================================
 * StudyEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const StudyEngine = {cards:[],currentIdx:0,isFlipped:!1,active:!1,_el:id=>document.getElementById(id),start(disasterType){var cards;0!==(cards=disasterType&&"all"!==disasterType?ALL_CARDS.filter(function(c){return c.disaster===disasterType}):ALL_CARDS.filter(function(c){return"equip"!==c.disaster})).length?(this.cards=cards.sort(function(){return Math.random()-.5}),this.currentIdx=0,this.isFlipped=!1,this.active=!0,PageManager.navigate("study"),this.render()):Modal.show("暂无卡片","该类型暂无知识卡","📝")},render(){if(this.cards&&0!==this.cards.length&&this.active)if(this.currentIdx>=this.cards.length)this.finish();else{var card=this.cards[this.currentIdx],zh=card.zh||{};this._el("studyProgressTxt").textContent="📖 学习中 "+(this.currentIdx+1)+"/"+this.cards.length,this._el("studyProgressFill").style.width=(this.currentIdx+1)/this.cards.length*100+"%",this._el("studyIcon").textContent=card.icon||"🌍",this._el("studyQuestion").textContent=zh.q||(card.zh?card.zh.name:card.icon||"..."),this._el("studyAnswerIcon").textContent="💡",this._el("studyAnswer").textContent=zh.opts?zh.opts[zh.ans]:"...",this._el("studyExp").textContent=zh.exp||card.explanation||"暂无解析",this._el("studyTips").textContent=card.tip||card.scenario||"暂无贴士",this._el("studyScenario").textContent=card.scenario||"暂无场景",this.isFlipped=!1;var inner=this._el("studyCardInner");inner&&(inner.style.transform="rotateY(0deg)"),this._el("studyPrevBtn").style.visibility=this.currentIdx>0?"visible":"hidden",this._el("studyNextBtn").textContent=this.currentIdx<this.cards.length-1?"下一张 ▶":"🎉 完成"}},flip(){this.isFlipped=!this.isFlipped;var inner=this._el("studyCardInner");inner&&(inner.style.transform=this.isFlipped?"rotateY(180deg)":"rotateY(0deg)"),AudioManager.play("click")},next(){this.currentIdx<this.cards.length-1?(this.currentIdx++,this.render(),AudioManager.play("click")):this.finish()},prev(){this.currentIdx>0&&(this.currentIdx--,this.render(),AudioManager.play("click"))},finish(){this.active=!1,Modal.show("🎉 学习完成！","你已浏览完所有 "+this.cards.length+" 张卡片！<br><br>要不要测试一下自己？","📚"),void 0!==GameState&&(GameState._data.stats.studyCompleted=(GameState._data.stats.studyCompleted||0)+1,GameState.save())},quit(){this.active=!1,PageManager.navigate("free")}};
