/**
 * ============================================================================
 * SupplyDropGame
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const SupplyDropGame = {_level:1,_score:0,_active:!1,_supplies:[{icon:"💊",name:"药品",color:"#FF5252"},{icon:"🍞",name:"食物",color:"#FFB300"},{icon:"💧",name:"饮用水",color:"#42A5F5"},{icon:"🧥",name:"衣物",color:"#66BB6A"},{icon:"🔦",name:"手电筒",color:"#AB47BC"}],_zones:[{icon:"🏥",name:"医疗区",needs:["💊"],color:"rgba(255,82,82,0.15)"},{icon:"🍽️",name:"食物区",needs:["🍞","💧"],color:"rgba(255,179,0,0.15)"},{icon:"🏠",name:"住宿区",needs:["🧥","🔦"],color:"rgba(102,187,106,0.15)"}],init(){this._level=1,this._score=0,this._active=!0,PageManager.navigate("supplydrop"),this._render()},_render(){var el=document.getElementById("supplydropContent");if(el){var supply=this._supplies[Math.floor(Math.random()*this._supplies.length)];this._currentSupply=supply;var html='<div class="v10-card" style="padding:20px;text-align:center;"><div style="font-size:0.75rem;color:rgba(255,255,255,0.4);margin-bottom:8px;">第 '+this._level+" 关 | 得分: "+this._score+'</div><div class="v10-progress" style="margin-bottom:16px;"><div class="v10-progress-fill" style="width:'+Math.min(100,10*this._level)+'%;"></div></div><div style="font-size:4rem;margin:20px 0;">'+supply.icon+'</div><div style="color:rgba(255,255,255,0.6);font-size:0.85rem;margin-bottom:20px;">将 <strong style="color:'+supply.color+'">'+supply.name+"</strong> 投放到正确的区域</div>";this._zones.forEach(function(zone,i){html+='<div class="v10-card" style="margin:8px 0;padding:16px;cursor:pointer;border:2px solid rgba(255,255,255,0.06);text-align:center;" onclick="SupplyDropGame.drop('+i+')"><span style="font-size:2rem;">'+zone.icon+'</span> <span style="color:rgba(255,255,255,0.7);margin-left:8px;">'+zone.name+'</span><div style="font-size:0.7rem;color:rgba(255,255,255,0.3);margin-top:4px;">需要: '+zone.needs.join(" ")+"</div></div>"}),html+="</div>",el.innerHTML=html}},drop(zoneIdx){if(this._active){var zone=this._zones[zoneIdx],supply=this._currentSupply;if(-1!==zone.needs.indexOf(supply.icon)){if(this._score+=10*this._level,this._level++,AudioManager.play("correct"),V10Toast.success("✅ 正确！+"+10*(this._level-1)),this._level>10)return void this._finish();setTimeout(function(){SupplyDropGame._render()},600)}else this._score=Math.max(0,this._score-5),AudioManager.play("wrong"),V10Toast.error("❌ 这个区域不需要"+supply.name)}},_finish(){this._active=!1,GameState.set("coins",(GameState.get("coins")||0)+this._score),Modal.show("🎯 投放任务完成","🏆 得分: "+this._score+"<br/>📦 完成 "+(this._level-1)+" 关<br/>💰 奖励: +"+this._score+" 金币","🎯")}};
