/**
 * ============================================================================
 * TimedChallengeEngine
 * ============================================================================
 * 
 *
 * Auto-generated from game.js refactoring.
 * ============================================================================
 */

const TimedChallengeEngine = {_time:30,_score:0,_total:0,_correct:0,_active:!1,_timer:null,init(){this._time=30,this._score=0,this._total=0,this._correct=0,this._active=!0,PageManager.navigate("timed"),this.render(),this._timer=setInterval(()=>{this._time--,this.updateTimer(),this._time<=0&&this.gameOver()},1e3),this.nextQuestion()},render(){document.getElementById("timedContent").innerHTML='<div class="v10-card" style="text-align:center;padding:20px 16px;"><div style="font-size:2rem;margin-bottom:4px;">⏱️</div><h3 style="margin:0 0 12px;color:rgba(255,255,255,0.9);">30秒限时挑战</h3><div style="display:flex;justify-content:center;gap:20px;margin-bottom:12px;"><div id="timedTimer" style="font-size:2.2rem;font-weight:800;color:#00D4FF;font-family:monospace;">30</div><div><div style="font-size:1.6rem;font-weight:800;color:#FFD700;">'+this._score+'</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);">得分</div></div><div><div style="font-size:1.6rem;font-weight:800;color:#00E676;">'+this._correct+"/"+this._total+'</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);">正确率</div></div></div><div id="timedQuiz"></div></div>'},updateTimer(){const el=document.getElementById("timedTimer");el&&(el.textContent=this._time,el.style.color=this._time<=5?"#F44336":this._time<=10?"#FF9800":"#00D4FF")},nextQuestion(){if(!this._active)return;var knowledgeCards=ALL_CARDS.filter(function(c){return"equip"!==c.disaster});const card=knowledgeCards[Math.floor(Math.random()*knowledgeCards.length)];this._currentCard=card;const optsHtml=card.zh.opts.map((o,i)=>'<div class="option-btn" onclick="TimedChallengeEngine.answer('+i+')" style="padding:8px 12px;margin:3px 0;background:rgba(255,255,255,0.04);border-radius:8px;border:1px solid rgba(255,255,255,0.06);cursor:pointer;text-align:left;color:rgba(255,255,255,0.85);font-size:0.8rem;"><span style="color:rgba(0,212,255,0.6);margin-right:6px;">'+["A","B","C","D"][i]+"</span>"+o+"</div>").join("");document.getElementById("timedQuiz").innerHTML='<div style="color:rgba(255,255,255,0.85);font-size:0.82rem;margin:6px 0;text-align:left;line-height:1.5;">'+card.zh.q+"</div>"+optsHtml},answer(idx){this._active&&(this._total++,idx===this._currentCard.zh.ans?(this._correct++,this._score+=10,AudioManager.play("correct"),V10Toast.success("+10")):AudioManager.play("wrong"),this.render(),this.nextQuestion())},gameOver(){this._active=!1,clearInterval(this._timer),this._correct>=15&&AchievementEngine.unlock("speed_demon"),GameState.set("timedBest",Math.max(this._score,GameState.get("timedBest")||0)),Modal.show("时间到！","📊 得分: "+this._score+"<br/>✅ 正确: "+this._correct+"/"+this._total+"<br/>🏆 历史最高: "+(GameState.get("timedBest")||0),"⏱️")}};
